# -*- coding: utf-8 -*-
"""
/***************************************************************************
 routeEditorDockWidget
                                 A QGIS plugin
 Edits and fits data to routes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2022 by drew
        email                : drew.bennett@ptsinternational.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtGui import QKeySequence
from PyQt5.QtWidgets import QMenuBar

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsFeature

from route_editor import route_model
from route_editor.widgets import layers_dialog




FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'route_editor_dockwidget_base.ui'))


class routeEditorDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(routeEditorDockWidget, self).__init__(parent)
        self.setupUi(self)
        
        self.mainView.setModel(route_model.routeModel())
        self.initLayersDialog()
        self.initTopMenu()





    def initLayersDialog(self):
        self.layersDialog = layers_dialog.layersDialog(parent=self)
        self.layersDialog.networkBox.layerChanged.connect(self.mainView.setNetworkLayer)
        self.layersDialog.labelBox.fieldChanged.connect(self.mainView.setLabelField)
        self.layersDialog.readingsBox.layerChanged.connect(self.mainView.setReadingsLayer)
        self.layersDialog.startChainageBox.fieldChanged.connect(self.mainView.setStartChainageField)
        self.layersDialog.endChainageBox.fieldChanged.connect(self.mainView.setEndChainageField)


        #set to current layers/fields
        self.mainView.setNetworkLayer(self.layersDialog.networkBox.currentLayer())
        self.mainView.setLabelField(self.layersDialog.labelBox.currentField())
        self.mainView.setReadingsLayer(self.layersDialog.readingsBox.currentLayer())
        self.mainView.setStartChainageField(self.layersDialog.startChainageBox.currentField())
        self.mainView.setEndChainageField(self.layersDialog.endChainageBox.currentField())       
        
        

    def initTopMenu(self):
        topMenu = QMenuBar()       


        #file
        fileMenu = topMenu.addMenu("File")
        saveAct = fileMenu.addAction('Save as...')
        saveAct.triggered.connect(self.save)

        openAct = fileMenu.addAction('Open...')
        openAct.triggered.connect(self.load)
        
        #insert
        insertMenu = topMenu.addMenu("Insert")

        insertFeatureAct = insertMenu.addAction('Insert Selected Feature')
        insertFeatureAct.setShortcut(QKeySequence('Alt+1'))#focus policy of dockwidget probably important here
        insertFeatureAct.setToolTip('Insert selected feature of layer')
        insertFeatureAct.triggered.connect(self.insertFeature)



        insertDummyAct = insertMenu.addAction('Insert Dummy')
        insertDummyAct.setShortcut(QKeySequence('Alt+2'))#focus policy of dockwidget probably important here
        insertDummyAct.triggered.connect(self.insertDummy)
        insertDummyAct.setToolTip('Insert dummy at row')


        insertFileAct = insertMenu.addAction('Insert File')
        insertFileAct.triggered.connect(self.insertFile)
        insertFileAct.setToolTip('Insert file...')


        setupMenu = topMenu.addMenu("Setup")
        setLayersAct = setupMenu.addAction('Set layers and fields')
        setLayersAct.setToolTip('Set layers and fields to be used by plugin')
        setLayersAct.triggered.connect(self.layersDialog.show)


        #help
        helpMenu = topMenu.addMenu('Help')  
        openHelpAct = helpMenu.addAction('Open help (in your default web browser)')
        openHelpAct.triggered.connect(self.openHelp)

        
        self.mainWidget.layout().setMenuBar(topMenu)
        
        

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()


    
    def getLayer(self):
        return self.layersDialog.networkBox.currentLayer()
        
        
    
    def getInsertRow(self):
        return self.rowBox.value()



    def load(self):
        pass
    
    
    
    def save(self):
        pass
    
    
    
    def insertDummy(self):
        self.mainView.model().insertDummy(row=self.getInsertRow())

    
    
    def insertFeature(self):
        layer = self.getLayer()
        feats = layer.selectedFeatures()
        
        if feats:
            f = feats[0]
        else:
            f = QgsFeature()

        self.mainView.model().insert(row=self.getInsertRow(),networkFeature=f)
        
        
    
    def insertFile(self):
        pass
    
    
    
    def openHelp(self):
        pass
    
